### ISSUE TITLE
分段模式的新需求

### ISSUE THREAD

**Issue by fengguixian** [WZF-Fei/ZFProgressView#1]
可不可以控制分段的数目和分段的长短？要不然如果进度条大的时候，会显得太稀疏。
![0b1de45b-747a-4b72-a6eb-a64352ca7ab2](https://cloud.githubusercontent.com/assets/3446543/10747637/7c8b0322-7c92-11e5-9679-413940846f08.png)

**Comment by WZF-Fei** [comment]
已修改。设置setGapWidth
